name: CI/CD to AWS ECR and EC1

on:
  push:
    branches:
      - dev
      - docs/hj-github-action-#24
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      # 체크아웃 / 리포지 상위 디렉토리로 자동 이동됨.
      - name: Checkout code
        uses: actions/checkout@v3

      # AWS ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}/frontend:latest .

      # Docker 이미지 푸시
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Check if the frontend container exists
            if docker ps -a --filter "name=frontend" --format '{{.Names}}' | grep -w frontend; then
              echo "Existing container found. Stopping and removing it..."
              docker stop frontend
              docker rm frontend
            else
              echo "No existing container found. Skipping stop and remove steps."
            fi

            # Pull the latest image
            docker pull ${{ secrets.ECR_REPOSITORY_URI }}/frontend:latest

            # Run the new container
            docker run -d --name frontend -p 3000:3000 ${{ secrets.ECR_REPOSITORY_URI }}/frontend:latest
